-- ============================================================================
-- CUTORA FISHES - SECURE DATABASE SCHEMA
-- Owner-Only Admin Access with Row Level Security
-- ============================================================================

-- 1. Profiles Table (User Data with Role Management)
-- ============================================================================
create table if not exists profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text unique,
  name text,
  role text default 'customer' check (role in ('owner', 'customer')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on profiles
alter table profiles enable row level security;

-- Profiles Policies
create policy "Users can view their own profile"
  on profiles for select
  using (auth.uid() = id);

create policy "Users can insert their own profile"
  on profiles for insert
  with check (auth.uid() = id);

create policy "Users can update their own profile"
  on profiles for update
  using (auth.uid() = id);

-- Owner can view all profiles
create policy "Owner can view all profiles"
  on profiles for select
  using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'owner'
    )
  );

-- 2. Products Table
-- ============================================================================
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric not null,
  image text,
  description text,
  cuts text[] default '{}',
  stock boolean default true,
  rating numeric default 4.5,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on products
alter table products enable row level security;

-- Products Policies
create policy "Anyone can view products"
  on products for select
  using (true);

-- Only owner can insert/update/delete products
create policy "Owner can insert products"
  on products for insert
  with check (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'owner'
    )
  );

create policy "Owner can update products"
  on products for update
  using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'owner'
    )
  );

create policy "Owner can delete products"
  on products for delete
  using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'owner'
    )
  );

-- 3. Orders Table (Enhanced with strict access control)
-- ============================================================================
create table if not exists orders (
  id text primary key,
  user_id uuid references auth.users on delete set null,
  user_email text,
  date timestamp with time zone default timezone('utc'::text, now()) not null,
  status text default 'Pending' check (status in ('Pending', 'Processing', 'Packed', 'Shipped', 'Delivered', 'Cancelled')),
  items jsonb not null,
  customer jsonb not null,
  item_total numeric not null,
  delivery_fee numeric default 0,
  taxes_and_charges numeric default 0,
  final_amount numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on orders
alter table orders enable row level security;

-- Orders Policies
-- Customers can only insert their own orders
create policy "Customers can insert their own orders"
  on orders for insert
  with check (
    auth.uid() = user_id
    or auth.role() = 'authenticated'
  );

-- Customers can only view their own orders
create policy "Customers can view their own orders"
  on orders for select
  using (
    auth.uid() = user_id
    or user_email = auth.jwt()->>'email'
  );

-- Owner can view ALL orders
create policy "Owner can view all orders"
  on orders for select
  using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'owner'
    )
  );

-- Owner can update ALL orders (for status changes)
create policy "Owner can update all orders"
  on orders for update
  using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'owner'
    )
  );

-- Owner can delete orders
create policy "Owner can delete orders"
  on orders for delete
  using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'owner'
    )
  );

-- 4. Database Trigger for Automatic Profile Creation
-- ============================================================================
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, name, role)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'name',
    'customer' -- Always default to customer, owner must be set manually
  );
  return new;
end;
$$;

-- Drop existing trigger if exists
drop trigger if exists on_auth_user_created on auth.users;

-- Create trigger to execute the function on INSERT into auth.users
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 5. Helper Function to Check if User is Owner
-- ============================================================================
create or replace function public.is_owner()
returns boolean
language sql
security definer
as $$
  select exists (
    select 1 from profiles
    where id = auth.uid() and role = 'owner'
  );
$$;

-- 6. Function to Get User Role
-- ============================================================================
create or replace function public.get_user_role()
returns text
language sql
security definer
as $$
  select role from profiles where id = auth.uid();
$$;

-- ============================================================================
-- INITIAL SETUP INSTRUCTIONS
-- ============================================================================
-- After running this schema:
-- 1. Create your owner account via the app's signup
-- 2. In Supabase Dashboard, run:
--    UPDATE profiles SET role = 'owner' WHERE email = 'your-owner-email@example.com';
-- 3. This will be the ONLY account with admin access
-- ============================================================================

-- Grant necessary permissions
grant usage on schema public to postgres, anon, authenticated, service_role;
grant all on all tables in schema public to postgres, anon, authenticated, service_role;
grant all on all sequences in schema public to postgres, anon, authenticated, service_role;
grant all on all routines in schema public to postgres, anon, authenticated, service_role;

create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  role text default 'customer',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table profiles enable row level security;

-- Policies
create policy "Public profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can insert their own profile" on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- 2. Products Table
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric not null,
  image text,
  description text,
  cuts text[] default '{}',
  stock boolean default true,
  rating numeric default 4.5,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Orders Table (Enhanced)
create table orders (
  id text primary key,
  user_id uuid references auth.users,  -- Link to authenticated user
  user_email text,                     -- Store email for reference
  date timestamp with time zone default timezone('utc'::text, now()) not null,
  status text default 'Placed',
  items jsonb not null,                -- Array of order items with details
  customer jsonb not null,             -- Customer information (name, phone, address, city, pincode)
  item_total numeric not null,         -- Subtotal of items
  delivery_fee numeric default 0,      -- Delivery charges
  taxes_and_charges numeric default 0, -- Additional taxes/charges
  final_amount numeric not null,       -- Total payable amount
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable RLS for Products/Orders
alter table products enable row level security;
alter table orders enable row level security;

-- Simple Policies for demo (Allow all access for simplicity, or refine as needed)
create policy "Enable read access for all users" on products for select using (true);
create policy "Enable insert for authenticated users only" on orders for insert with check (auth.role() = 'authenticated');
create policy "Users can view their own orders" on orders for select using (
  auth.uid() = user_id OR user_email = auth.jwt()->>'email'
);
create policy "Admins can view all orders" on orders for select using (
  (auth.jwt()->>'role')::text = 'admin'
);

-- 5. Database Trigger for Automatic Profile Creation
-- This trigger automatically creates a profile entry when a new user signs up via Supabase Auth.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'name', 'customer');
  return new;
end;
$$;

-- Trigger to execute the function on INSERT into auth.users
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user(); 
